/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Erc20__factory } from './Erc20__factory'
export { MilkyWay__factory } from './MilkyWay__factory'
export { Multicall__factory } from './Multicall__factory'
export { Pair__factory } from './Pair__factory'
export { Presale__factory } from './Presale__factory'
export { Referral__factory } from './Referral__factory'
export { Staking__factory } from './Staking__factory'
export { SwapRouter__factory } from './SwapRouter__factory'
